### ISSUE TITLE
Can you please provide details on how to use this functionality ?

### ISSUE THREAD

**Issue by syedjafer** [renefritze/python-watchdog#1]
Can you please provide details on how to use this functionality ?

**Comment by renefritze** [comment]
Have a look at https://github.com/renefritze/python-watchdog/blob/master/watchdog.py#L17
If you ran `watchdog.py` it would periodically check if any process exceeds the mem percentage threshold and kill it.
It could still work if you run it through 2to3.

Ofc this code is almost 10 years old, and you'd probably be better off doing this with cgroups instead.

**Comment by syedjafer** [comment]
👍
